const ideas={
  parler:{label:'parler français',complement:'français',aux:'avoir',pp:'parlé',present:{je:'parle',tu:'parles',il:'parle',elle:'parle',on:'parle',nous:'parlons',vous:'parlez',ils:'parlent',elles:'parlent'},imparfait:{je:'parlais',tu:'parlais',il:'parlait',elle:'parlait',on:'parlait',nous:'parlions',vous:'parliez',ils:'parlaient',elles:'parlaient'},meaning:{present:'Speak French now, habitually, or generally.',passe:'Spoke French as a completed event.',imparfait:'Was speaking French or used to speak French.'}},
  manger:{label:'manger au restaurant',complement:'au restaurant',aux:'avoir',pp:'mangé',present:{je:'mange',tu:'manges',il:'mange',elle:'mange',on:'mange',nous:'mangeons',vous:'mangez',ils:'mangent',elles:'mangent'},imparfait:{je:'mangeais',tu:'mangeais',il:'mangeait',elle:'mangeait',on:'mangeait',nous:'mangions',vous:'mangiez',ils:'mangeaient',elles:'mangeaient'},meaning:{present:'Eat or are eating at the restaurant.',passe:'Ate at the restaurant; the meal is treated as completed.',imparfait:'Was eating or used to eat at the restaurant.'}},
  finir:{label:'finir le travail',complement:'le travail',aux:'avoir',pp:'fini',present:{je:'finis',tu:'finis',il:'finit',elle:'finit',on:'finit',nous:'finissons',vous:'finissez',ils:'finissent',elles:'finissent'},imparfait:{je:'finissais',tu:'finissais',il:'finissait',elle:'finissait',on:'finissait',nous:'finissions',vous:'finissiez',ils:'finissaient',elles:'finissaient'},meaning:{present:'Finish or are finishing the work.',passe:'Finished the work.',imparfait:'Was finishing or used to finish the work.'}},
  faire:{label:'faire ça',complement:'ça',aux:'avoir',pp:'fait',present:{je:'fais',tu:'fais',il:'fait',elle:'fait',on:'fait',nous:'faisons',vous:'faites',ils:'font',elles:'font'},imparfait:{je:'faisais',tu:'faisais',il:'faisait',elle:'faisait',on:'faisait',nous:'faisions',vous:'faisiez',ils:'faisaient',elles:'faisaient'},meaning:{present:'Do or are doing that.',passe:'Did that as a completed action.',imparfait:'Was doing that or used to do that.'}},
  aller:{label:'aller au magasin',complement:'au magasin',aux:'etre',pp:'allé',present:{je:'vais',tu:'vas',il:'va',elle:'va',on:'va',nous:'allons',vous:'allez',ils:'vont',elles:'vont'},imparfait:{je:'allais',tu:'allais',il:'allait',elle:'allait',on:'allait',nous:'allions',vous:'alliez',ils:'allaient',elles:'allaient'},meaning:{present:'Go or are going to the store.',passe:'Went to the store as a completed trip.',imparfait:'Was going or used to go to the store.'}},
  venir:{label:'venir avec nous',complement:'avec nous',aux:'etre',pp:'venu',present:{je:'viens',tu:'viens',il:'vient',elle:'vient',on:'vient',nous:'venons',vous:'venez',ils:'viennent',elles:'viennent'},imparfait:{je:'venais',tu:'venais',il:'venait',elle:'venait',on:'venait',nous:'venions',vous:'veniez',ils:'venaient',elles:'venaient'},meaning:{present:'Come or are coming with us.',passe:'Came with us as a completed event.',imparfait:'Was coming or used to come with us.'}},
  avoir:{label:'avoir le temps',complement:'le temps',aux:'avoir',pp:'eu',present:{je:'ai',tu:'as',il:'a',elle:'a',on:'a',nous:'avons',vous:'avez',ils:'ont',elles:'ont'},imparfait:{je:'avais',tu:'avais',il:'avait',elle:'avait',on:'avait',nous:'avions',vous:'aviez',ils:'avaient',elles:'avaient'},meaning:{present:'Have time.',passe:'Had time on a bounded occasion or obtained the time needed.',imparfait:'Had time or used to have time as an ongoing situation.'}},
  etre:{label:'être prêt(e)',complement:'prêt(e)',complements:{je:'prêt(e)',tu:'prêt(e)',il:'prêt',elle:'prête',on:'prêt(e)(s)',nous:'prêt(e)s',vous:'prêt(e)(s)',ils:'prêts',elles:'prêtes'},aux:'avoir',pp:'été',present:{je:'suis',tu:'es',il:'est',elle:'est',on:'est',nous:'sommes',vous:'êtes',ils:'sont',elles:'sont'},imparfait:{je:'étais',tu:'étais',il:'était',elle:'était',on:'était',nous:'étions',vous:'étiez',ils:'étaient',elles:'étaient'},meaning:{present:'Be ready now.',passe:'Was ready in a bounded, completed situation; possible, but less common for simple background description.',imparfait:'Was or used to be ready; usually the natural form for a past state.'}},
  pouvoir:{label:'pouvoir venir',complement:'venir',aux:'avoir',pp:'pu',present:{je:'peux',tu:'peux',il:'peut',elle:'peut',on:'peut',nous:'pouvons',vous:'pouvez',ils:'peuvent',elles:'peuvent'},imparfait:{je:'pouvais',tu:'pouvais',il:'pouvait',elle:'pouvait',on:'pouvait',nous:'pouvions',vous:'pouviez',ils:'pouvaient',elles:'pouvaient'},meaning:{present:'Can come now or generally.',passe:'Managed to come or succeeded in coming.',imparfait:'Could come or had the ability/opportunity to come.'}},
  vouloir:{label:'vouloir partir',complement:'partir',aux:'avoir',pp:'voulu',present:{je:'veux',tu:'veux',il:'veut',elle:'veut',on:'veut',nous:'voulons',vous:'voulez',ils:'veulent',elles:'veulent'},imparfait:{je:'voulais',tu:'voulais',il:'voulait',elle:'voulait',on:'voulait',nous:'voulions',vous:'vouliez',ils:'voulaient',elles:'voulaient'},meaning:{present:'Want to leave.',passe:'Tried, decided, or made an attempt to leave.',imparfait:'Wanted to leave as an ongoing desire.'}},
  devoir:{label:'devoir travailler',complement:'travailler',aux:'avoir',pp:'dû',present:{je:'dois',tu:'dois',il:'doit',elle:'doit',on:'doit',nous:'devons',vous:'devez',ils:'doivent',elles:'doivent'},imparfait:{je:'devais',tu:'devais',il:'devait',elle:'devait',on:'devait',nous:'devions',vous:'deviez',ils:'devaient',elles:'devaient'},meaning:{present:'Have to work.',passe:'Had to work; the necessity is treated as completed.',imparfait:'Had to or was supposed to work as background.'}},
  prendre:{label:'prendre le bus',complement:'le bus',aux:'avoir',pp:'pris',present:{je:'prends',tu:'prends',il:'prend',elle:'prend',on:'prend',nous:'prenons',vous:'prenez',ils:'prennent',elles:'prennent'},imparfait:{je:'prenais',tu:'prenais',il:'prenait',elle:'prenait',on:'prenait',nous:'prenions',vous:'preniez',ils:'prenaient',elles:'prenaient'},meaning:{present:'Take or are taking the bus.',passe:'Took the bus on a completed trip.',imparfait:'Was taking or used to take the bus.'}},
  voir:{label:'voir le film',complement:'le film',aux:'avoir',pp:'vu',present:{je:'vois',tu:'vois',il:'voit',elle:'voit',on:'voit',nous:'voyons',vous:'voyez',ils:'voient',elles:'voient'},imparfait:{je:'voyais',tu:'voyais',il:'voyait',elle:'voyait',on:'voyait',nous:'voyions',vous:'voyiez',ils:'voyaient',elles:'voyaient'},meaning:{present:'See or are watching the movie.',passe:'Saw the movie as a completed event.',imparfait:'Was seeing/watching or used to watch the movie.'}},
  mettre:{label:'mettre ça ici',complement:'ça ici',aux:'avoir',pp:'mis',present:{je:'mets',tu:'mets',il:'met',elle:'met',on:'met',nous:'mettons',vous:'mettez',ils:'mettent',elles:'mettent'},imparfait:{je:'mettais',tu:'mettais',il:'mettait',elle:'mettait',on:'mettait',nous:'mettions',vous:'mettiez',ils:'mettaient',elles:'mettaient'},meaning:{present:'Put or are putting that here.',passe:'Put that here as a completed action.',imparfait:'Was putting or used to put that here.'}}
};
